In [2]:
import pandas as pd
import newspaper
from newspaper import Article

In [3]:
#Edgewater Technology
url1='http://www.nytimes.com/2000/12/28/us/man-charged-in-killings-evaded-strict-gun-laws.html'
url2='http://www.nytimes.com/2000/12/27/us/7-die-in-rampage-at-company-co-worker-of-victims-arrested.html'
urls=[url1, url2]
Nyt_ET =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_ET= Nyt_ET.append([[a.title, a.text]], ignore_index=True)
Nyt_ET.columns=['Title','Article']
Nyt_ET['Incident Name'] = 'Edgewater Techology'
Nyt_ET['Shooter Race']='White'
Nyt_ET

,Title,Article,Incident Name,Shooter Race
0,Man Charged In Killings Evaded Strict Gun Laws,If the man accused of killing seven people nea...,Edgewater Techology,White
1,7 Die in Rampage at Company; Co-Worker of Vict...,"''There were receptionists, for God's sake!'' ...",Edgewater Techology,White

In [4]:
url=['No Articles'] # Appalachian School oF Law
Nyt_ASL =pd.DataFrame()
for i in url: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_ASL= Nyt_ASL.append([[a.title, a.text]], ignore_index=True)
Nyt_ASL.columns=['Title','Article']
Nyt_ASL['title'] = 'NaN'
Nyt_ASL['article'] = 'NaN'
Nyt_ASL['Incident Name'] = 'Appalachian School of Law'
Nyt_ASL.drop(['Title','Article'], axis=1, inplace=True)
Nyt_ASL.rename(index=str, columns={'title':'Title','article':'Article'}, inplace=True)
Nyt_ASL

Traceback (most recent call last):
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
XMLSyntaxError: line 1100: Tag nav invalid

  Title Article              Incident Name
0   NaN     NaN  Appalachian School of Law

In [5]:
#Navistar International Shooting
url3='http://www.nytimes.com/2001/02/07/us/gunman-s-life-came-undone-in-years-before-the-shootings.html'
url4='http://www.nytimes.com/2001/02/06/us/ex-worker-opens-fire-at-illinois-plant-5-are-killed.html'
urls=[url3, url4]
Nyt_NI =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_NI= Nyt_NI.append([[a.title, a.text]], ignore_index=True)
Nyt_NI.columns=['Title','Article']
Nyt_NI['Incident Name'] = 'Navister International'
Nyt_NI['Shooter Race']='African American'
Nyt_NI

,Title,Article,Incident Name,Shooter Race
0,Gunman's Life Came Undone In Years Before the ...,"Mr. Baker's lawyer, Charles K. Piet, said he s...",Navister International,African American
1,Ex-Worker Opens Fire at Illinois Plant; 5 Are ...,When the security guard refused Mr. Baker entr...,Navister International,African American

In [6]:
#Santana HS
url27='http://www.nytimes.com/2001/03/06/us/young-suspect-s-mother-asks-oh-god-why.html'
url28='http://www.nytimes.com/2001/03/06/opinion/guns-in-young-hands.html'
url29='http://www.nytimes.com/2001/03/06/us/shooting-at-school-leaves-2-dead-and-13-hurt.html'
url30='http://www.nytimes.com/2001/03/07/opinion/l-grim-lessons-at-santana-high-284211.html'
url31='http://www.nytimes.com/2001/03/07/opinion/l-grim-lessons-at-santana-high-284238.html'
url32='http://www.nytimes.com/2001/03/07/opinion/l-grim-lessons-at-santana-high-284254.html'
url33='http://www.nytimes.com/2001/03/07/us/shooting-was-planned-and-calmly-carried-out-police-say.html'
url34='http://www.nytimes.com/2001/03/07/opinion/l-grim-lessons-at-santana-high-284203.html'
url35='http://www.nytimes.com/2001/03/07/us/rampage-took-the-lives-of-a-trouper-and-of-the-nicest-guy-in-the-world.html'
url36='http://www.nytimes.com/2001/03/07/opinion/l-grim-lessons-at-santana-high-284220.html'
url37='http://www.nytimes.com/2001/03/07/us/plenty-of-vivid-adjectives-but-no-answers-in-killings.html'
url38='http://www.nytimes.com/2001/03/08/opinion/threats-of-school-violence.html'
url39='http://www.nytimes.com/2001/03/08/us/student-held-in-shootings-is-in-court-as-school-resumes.html'
url40='http://www.nytimes.com/2001/03/09/opinion/l-get-to-troubled-kids-before-they-start-shooting-320196.html'
url41='http://www.nytimes.com/2001/03/09/opinion/l-get-to-troubled-kids-before-they-start-shooting-320200.html'
url42='http://www.nytimes.com/2001/03/09/opinion/l-get-to-troubled-kids-before-they-start-shooting-320226.html'
url43='http://www.nytimes.com/2001/03/09/opinion/l-get-to-troubled-kids-before-they-start-shooting-320218.html'
url44='http://www.nytimes.com/2001/03/09/us/santee-is-latest-blow-to-myth-of-suburbia-s-safer-schools.html'
url45='http://www.nytimes.com/2001/03/10/us/from-almost-famous-to-ordinary-in-3-days.html'
url46='http://www.nytimes.com/2001/03/10/opinion/a-brain-too-young-for-good-judgment.html'
url47='https://learning.blogs.nytimes.com/2001/03/12/big-bang-theory/'
url48='http://www.nytimes.com/2001/03/11/us/others-tragedies-helped-santee-prepare-for-its-own.html'
urls=[url27, url28,url29,url30,url31,url32,url33,url34,url35,url36,url37,url38,url39,url40,url41,url42,
     url43,url44,url45,url46,url47,url48]
Nyt_SHS =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_SHS= Nyt_SHS.append([[a.title, a.text]], ignore_index=True)
Nyt_SHS.columns=['Title','Article']
Nyt_SHS['Incident Name'] = 'Santana High School'
Nyt_SHS['Shooter Race']='White'
Nyt_SHS

,Title,Article,Incident Name,Shooter Race
0,"Young Suspect's Mother Asks, 'Oh, God. Why?'",She spoke calmly and gave terse replies to a r...,Santana High School,White
1,Guns in Young Hands,The school shooting in suburban San Diego yest...,Santana High School,White
2,Shooting at School Leaves 2 Dead and 13 Hurt,Witnesses described pandemonium and panic as t...,Santana High School,White
3,Grim Lessons at Santana High,To the Editor:\n\nRe ''Shooting at School Leav...,Santana High School,White
4,Grim Lessons at Santana High,To the Editor:\n\nRe ''Guns in Young Hands'' (...,Santana High School,White
5,Grim Lessons at Santana High,To the Editor:\n\nRe ''Shooting at School Leav...,Santana High School,White
6,"Shooting Was Planned and Calmly Carried Out, P...",The officer who arrested Mr. Williams said tha...,Santana High School,White
7,Grim Lessons at Santana High,To the Editor:\n\nRe ''Shooting at School Leav...,Santana High School,White
8,Rampage Took the Lives of a 'Trouper' and of '...,One friend said that when he learned of Bryan'...,Santana High School,White
9,Grim Lessons at Santana High,To the Editor:\n\nRe ''Guns in Young Hands'' (...,Santana High School,White
10,Plenty of Vivid Adjectives But No Answers in K...,"''We don't know if he was mad at the school, m...",Santana High School,White
11,Threats of School Violence,Monday's shooting at Santana High School in Sa...,Santana High School,White
12,Student Held in Shootings Is in Court as Schoo...,"His two public defenders, one on each side of ...",Santana High School,White
13,Get to Troubled Kids Before They Start Shooting,To the Editor:\n\nRe ''Student Held in Shootin...,Santana High School,White
14,Get to Troubled Kids Before They Start Shooting,To the Editor:\n\nRe ''Threats of School Viole...,Santana High School,White
15,Get to Troubled Kids Before They Start Shooting,To the Editor:\n\nRe ''Plenty of Vivid Adjecti...,Santana High School,White
16,Get to Troubled Kids Before They Start Shooting,To the Editor:\n\nRe ''Threats of School Viole...,Santana High School,White
17,Santee Is Latest Blow to Myth Of Suburbia's Sa...,"Until Monday, a persistent ''It can't happen h...",Santana High School,White
18,From Almost Famous to Ordinary in 3 Days,It has become a part of the ritualization of t...,Santana High School,White
19,A Brain Too Young for Good Judgment,Many factors can impair the capacity of the pr...,Santana High School,White
20,The New York Times,Note: This lesson was originally published on ...,Santana High School,White
21,Others' Tragedies Helped Santee Prepare for It...,"[On Saturday, a funeral was held for one of th...",Santana High School,White

In [7]:
#University of Arizona
url5='http://www.nytimes.com/2002/10/29/us/student-kills-3-instructors-and-himself-at-u-of-arizona.html'
Nyt_UofA =pd.DataFrame()
a=Article(url5, language='en')
a.download()
a.parse()
Nyt_UofA= Nyt_UofA.append([[a.title, a.text]], ignore_index=True)
Nyt_UofA.columns=['Title','Article']
Nyt_UofA['Incident Name'] = 'University of Arizona'
Nyt_UofA['Shooter Race']='Latin American'
Nyt_UofA

,Title,Article,Incident Name,Shooter Race
0,Student Kills 3 Instructors and Himself at U. ...,"But before they responded, the police said, Mr...",University of Arizona,Latin American

In [8]:
#Case Western Reserve Shooting
url6='http://www.nytimes.com/2003/05/11/us/ex-employee-held-in-campus-attack.html'
Nyt_CARU =pd.DataFrame()
a=Article(url6, language='en')
a.download()
a.parse()
Nyt_CARU= Nyt_CARU.append([[a.title, a.text]], ignore_index=True)
Nyt_CARU.columns=['Title','Article']
Nyt_CARU['Incident Name'] = 'Case Western Reserve'
Nyt_CARU['Shooter Race']='Asian'
Nyt_CARU

,Title,Article,Incident Name,Shooter Race
0,Ex-Employee Held in Campus Attack,In letters to Cleveland officials posted on th...,Case Western Reserve,Asian

In [9]:
#Lockhed Martin Shooting
url7='http://www.nytimes.com/2003/07/09/us/man-kills-5-co-workers-at-plant-and-himself.html'
url8='http://www.nytimes.com/2003/07/10/us/factory-killer-had-a-known-history-of-anger-and-racial-taunts.html'
urls=[url7, url8]
Nyt_LM =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_LM= Nyt_LM.append([[a.title, a.text]], ignore_index=True)
Nyt_LM.columns=['Title','Article']
Nyt_LM['Incident Name'] = 'Lockheed Martin'
Nyt_LM['Shooter Race']='White'
Nyt_LM

,Title,Article,Incident Name,Shooter Race
0,Man Kills 5 Co-Workers at Plant and Himself,"''He was trying to shoot Steve Cobb, the plant...",Lockheed Martin,White
1,Factory Killer Had a Known History of Anger an...,Co-workers said Mr. Williams's racial prejudic...,Lockheed Martin,White

In [10]:
#Windy City Core Supply
url9='http://www.nytimes.com/2003/08/28/us/man-fired-by-warehouse-kills-6-of-its-9-employees.html'
Nyt_WCC =pd.DataFrame()
a=Article(url9, language='en')
a.download()
a.parse()
Nyt_WCC= Nyt_WCC.append([[a.title, a.text]], ignore_index=True)
Nyt_WCC.columns=['Title','Article']
Nyt_WCC['Incident Name'] = 'Windy City Core Supply'
Nyt_WCC['Shooter Race']='Latin American'
Nyt_WCC

,Title,Article,Incident Name,Shooter Race
0,Man Fired by Warehouse Kills 6 of Its 9 Employees,The police said Mr. Tapia had made threatening...,Windy City Core Supply,Latin American

In [11]:
#Birchwood Wisconsin
url=['No Articles'] 
Nyt_BW =pd.DataFrame()
for i in url: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_BW= Nyt_BW.append([[a.title, a.text]], ignore_index=True)
Nyt_BW.columns=['Title','Article']
Nyt_BW['title'] = 'NaN'
Nyt_BW['article'] = 'NaN'
Nyt_BW['Incident Name'] = 'Birchwood, Wisconsin'
Nyt_BW.drop(['Title','Article'], axis=1, inplace=True)
Nyt_BW.rename(index=str, columns={'title':'Title','article':'Article'}, inplace=True)
Nyt_BW

Traceback (most recent call last):
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
XMLSyntaxError: line 1086: Tag nav invalid

  Title Article         Incident Name
0   NaN     NaN  Birchwood, Wisconsin

In [12]:
#Alrosa Villa Shoooting
url10='http://www.nytimes.com/2004/12/10/us/after-a-concert-shooting-a-who-but-not-a-why.html'
url11='http://www.nytimes.com/2004/12/10/arts/music/darrell-abbott-38-a-guitarist-featured-in-heavymetal-bands-dies.html'
url12='http://www.nytimes.com/2004/12/11/us/taped-calls-describe-chaotic-scene-at-ohio-nightclub-shooting.html'
url13='http://www.nytimes.com/2004/12/11/arts/dimebag-darrells-fans-fill-heavymetal-sites-with-internet-eulogies.html'
urls=[url10, url11,url12,url13]
Nyt_AV =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_AV= Nyt_AV.append([[a.title, a.text]], ignore_index=True)
Nyt_AV.columns=['Title','Article']
Nyt_AV['Incident Name'] = 'Alrosa Villa'
Nyt_AV['Shooter Race']='White'
Nyt_AV

,Title,Article,Incident Name,Shooter Race
0,"After a Concert Shooting, a 'Who' but Not a 'Why'",The police said they were chasing down tips th...,Alrosa Villa,White
1,"Darrell Abbott, 38, a Guitarist Featured in He...","Correction Appended\n\nDarrell Abbott, the bee...",Alrosa Villa,White
2,Taped Calls Describe Chaotic Scene at Ohio Nig...,As a man jumped onto a nightclub stage in Colu...,Alrosa Villa,White
3,Dimebag Darrell's Fans Fill Heavy-Metal Sites ...,"The band's official fan Web site, damageplan.n...",Alrosa Villa,White

In [13]:
#Brookfield Shooting
url14='http://www.nytimes.com/2005/03/18/us/rampage-puts-spotlight-on-a-church-community.html'
url15='https://query.nytimes.com/gst/fullpage.html?res=9B0CE5DC153CF930A25750C0A9639C8B63'
url16='http://www.nytimes.com/2005/03/14/us/after-shootings-in-wisconsin-a-community-asks-why.html'
url17='http://www.nytimes.com/2005/03/15/us/police-focus-on-religion-in-milwaukee-shootings.html'
urls=[url14, url15,url16,url17]
Nyt_Brook =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_Brook= Nyt_Brook.append([[a.title, a.text]], ignore_index=True)
Nyt_Brook.columns=['Title','Article']
Nyt_Brook['Incident Name'] = 'Living Church of God'
Nyt_Brook['Shooter Race']='White'
Nyt_Brook

,Title,Article,Incident Name,Shooter Race
0,Rampage Puts Spotlight on a Church Community,"Glen Gilchrist, a church pastor for Arizona an...",Living Church of God,White
1,GUNMAN KILLS 7 IN CHURCH GROUP NEAR MILWAUKEE,An evangelical church meeting turned chaotic a...,Living Church of God,White
2,"After Shootings in Wisconsin, a Community Asks...","""Sometimes he was up and sometimes he was down...",Living Church of God,White
3,Police Focus on Religion in Milwaukee Shootings,"Investigators are combing through some 1,000 e...",Living Church of God,White

In [14]:
#RedLake HS
url18='https://query.nytimes.com/gst/fullpage.html?res=9C0CE4DA1F3CF931A15750C0A9639C8B63'
url19='http://www.nytimes.com/2005/03/26/us/family-wonders-if-prozac-prompted-school-shootings.html'
url20='http://www.nytimes.com/2005/03/25/us/survivors-of-high-school-rampage-left-with-injuries-and-questions.html'
url21='http://www.nytimes.com/2005/03/24/us/days-after-killings-a-tribe-seeks-a-cloak-of-privacy-for-its-grief.html'
url22='http://www.nytimes.com/2005/03/24/us/signs-of-danger-were-missed-in-a-troubled-teenagers-life.html'
url23='https://learning.blogs.nytimes.com/2005/03/23/nightmare-in-minnesota/'
url24='http://www.nytimes.com/2005/03/23/us/eerie-parallels-are-seen-to-shootings-at-columbine.html'
url25='http://www.nytimes.com/2005/03/23/us/behind-the-why-of-a-rampage-loner-with-a-taste-for-nazism.html'
url26='http://www.nytimes.com/2005/03/27/us/tribe-buries-3-on-a-long-road-to-healing.html'
urls=[url18, url19,url20,url21,url22,url23,url24,url25,url26]
Nyt_RHS =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_RHS= Nyt_RHS.append([[a.title, a.text]], ignore_index=True)
Nyt_RHS.columns=['Title','Article']
Nyt_RHS['Incident Name'] = 'Red Lake High School'
Nyt_RHS['Shooter Race']='Native American or Alaska Native'
Nyt_RHS

,Title,Article,Incident Name,Shooter Race
0,Shooting Rampage by Student Leaves 10 Dead on ...,Correction Appended\n\nA high school student w...,Red Lake High School,Native American or Alaska Native
1,Family Wonders if Prozac Prompted School Shoot...,The effects of antidepressants on young people...,Red Lake High School,Native American or Alaska Native
2,Survivors of High School Rampage Left With Inj...,"Cody, who spoke to reporters on Thursday from ...",Red Lake High School,Native American or Alaska Native
3,"Days After Killings, a Tribe Seeks a Cloak of ...","""We didn't ask for those boundaries -- they we...",Red Lake High School,Native American or Alaska Native
4,Signs of Danger Were Missed in a Troubled Teen...,"Beyond the outward signs of stress, however, t...",Red Lake High School,Native American or Alaska Native
5,Nightmare in Minnesota,Note: This lesson was originally published on ...,Red Lake High School,Native American or Alaska Native
6,Eerie Parallels Are Seen to Shootings at Colum...,"Beyond these particular similarities, experts ...",Red Lake High School,Native American or Alaska Native
7,"Behind the Why of a Rampage, Loner With a Tast...","The school, which serves about 300 students, w...",Red Lake High School,Native American or Alaska Native
8,Tribe Buries 3 on a Long Road to Healing,It was Sergeant Lussier's 16-year-old grandson...,Red Lake High School,Native American or Alaska Native

In [15]:
#Goleta PO
url49='http://www.nytimes.com/2006/02/03/us/woman-in-california-postal-shootings-had-history-of-bizarre-behavior.html'
Nyt_GPO =pd.DataFrame()
a=Article(url49, language='en')
a.download()
a.parse()
Nyt_GPO= Nyt_GPO.append([[a.title, a.text]], ignore_index=True)
Nyt_GPO.columns=['Title','Article']
Nyt_GPO['Incident Name'] = 'Goleta Post Office'
Nyt_GPO['Shooter Race']='White'
Nyt_GPO

,Title,Article,Incident Name,Shooter Race
0,Woman in California Postal Shootings Had Histo...,"""It seemed liked she was acting delusional,"" M...",Goleta Post Office,White

In [16]:
#Seattle House Party
url50='http://www.nytimes.com/2006/03/26/us/7-dead-in-shooting-at-seattle-house-party.html'
Nyt_SHP =pd.DataFrame()
a=Article(url50, language='en')
a.download()
a.parse()
Nyt_SHP= Nyt_SHP.append([[a.title, a.text]], ignore_index=True)
Nyt_SHP.columns=['Title','Article']
Nyt_SHP['Incident Name'] = 'Seattle House Party'
Nyt_SHP['Shooter Race']='White'
Nyt_SHP

,Title,Article,Incident Name,Shooter Race
0,7 Dead in Shooting at Seattle House Party,He then spotted the gunman standing outside th...,Seattle House Party,White

In [17]:
#Essex Elementary
url51='http://www.nytimes.com/2006/08/25/us/25brfs-002.html'
Nyt_EES =pd.DataFrame()
a=Article(url51, language='en')
a.download()
a.parse()
Nyt_EES= Nyt_EES.append([[a.title, a.text]], ignore_index=True)
Nyt_EES.columns=['Title','Article']
Nyt_EES['Incident Name'] = 'Essex Elementary School'
Nyt_EES['Shooter Race']='African American'
Nyt_EES

,Title,Article,Incident Name,Shooter Race
0,Vermont: Gunman Kills Two,"Hours after breaking up with his girlfriend, a...",Essex Elementary School,African American

In [18]:
#Orange HS
url52='http://www.nytimes.com/2006/09/01/us/01shooting.html'
Nyt_OHS =pd.DataFrame()
a=Article(url52, language='en')
a.download()
a.parse()
Nyt_OHS= Nyt_OHS.append([[a.title, a.text]], ignore_index=True)
Nyt_OHS.columns=['Title','Article']
Nyt_OHS['Incident Name'] = 'Orange High School'
Nyt_OHS['Shooter Race']='Latin American'
Nyt_OHS

,Title,Article,Incident Name,Shooter Race
0,Teenager Is Accused of Multiple Shootings,"HILLSBOROUGH, N.C., Aug. 31 (AP) — A teenager ...",Orange High School,Latin American

In [19]:
#Duquesne University
url53='http://www.nytimes.com/2006/09/19/us/19duquesne.html'
url54='http://www.nytimes.com/2006/09/19/us/19cnd-shoot.html'
url55='http://www.nytimes.com/2006/09/20/us/20duquesne.html'
url56='http://www.nytimes.com/2006/09/21/us/21duquesne.html'
urls=[url53, url54,url55,url56]
Nyt_DU =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_DU= Nyt_DU.append([[a.title, a.text]], ignore_index=True)
Nyt_DU.columns=['Title','Article']
Nyt_DU['Incident Name'] = 'Duquesne University'
Nyt_DU['Shooter Race']='African American'
Nyt_DU

,Title,Article,Incident Name,Shooter Race
0,An Eerie Quiet at Duquesne After 5 Students Ar...,Mr. Dougherty added that while officials would...,Duquesne University,African American
1,Suspect Held in Duquesne Shooting,"PITTSBURGH, Sept. 19 — A man suspected in the ...",Duquesne University,African American
2,"After Arrest, a 2nd Suspect Is Sought in Duque...",The other person being sought was identified a...,Duquesne University,African American
3,2nd Arrest Is Made in Duquesne Attack,"By The New York Times\n\nPITTSBURGH, Sept. 20 ...",Duquesne University,African American

In [20]:
#Amish School
url61='http://www.nytimes.com/2006/10/02/us/03amishcnd.html'
url62='http://www.nytimes.com/2006/10/03/us/04amishcnd.html'
url63='http://www.nytimes.com/2006/10/03/opinion/03tue4.html'
url64='http://www.nytimes.com/2006/10/03/us/03amish.html'
url65='http://www.nytimes.com/2006/10/04/us/04amish.html'
url66='http://www.nytimes.com/2006/10/04/us/04children.html'
url67='http://www.nytimes.com/2006/10/05/us/05amish.html'
urls=[url61, url62,url63,url64,url65,url66,url67]
Nyt_Amish =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_Amish= Nyt_Amish.append([[a.title, a.text]], ignore_index=True)
Nyt_Amish.columns=['Title','Article']
Nyt_Amish['Incident Name'] = 'West Nickel Mines Amish School'
Nyt_Amish['Shooter Race']='White'
Nyt_Amish

,Title,Article,Incident Name,Shooter Race
0,Students Killed by Gunman at Amish Schoolhouse,A lone gunman walked into a one-room schoolhou...,West Nickel Mines Amish School,White
1,Gunman May Have Planned Abuse,"Five more girls were wounded Monday, and some ...",West Nickel Mines Amish School,White
2,Three School Shootings,No one will rise up to defend a man who walks ...,West Nickel Mines Amish School,White
3,"Man Shoots 11, Killing 5 Girls, in Amish School",Mr. Roberts had no criminal record or history ...,West Nickel Mines Amish School,White
4,Strong Faith and Community May Help Amish Cope...,"About 28,000 Amish live in Lancaster County, a...",West Nickel Mines Amish School,White
5,Police Describe Gunman’s Plan in School Siege,With their traditional garb and religious dict...,West Nickel Mines Amish School,White
6,Amish School Survivors Struggle After Killings,“They talked with this gunman and asked him wh...,West Nickel Mines Amish School,White

In [21]:
#Trolley Square UT
url57='http://www.nytimes.com/2007/02/13/us/14slaycnd.html'
url58='http://www.nytimes.com/2007/02/13/us/13slay.html'
url59='http://www.nytimes.com/2007/02/14/us/14mall.html'
url60='http://www.nytimes.com/2007/02/15/us/15mall.html'
urls=[url57, url58,url59,url60]
Nyt_TSUT =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_TSUT= Nyt_TSUT.append([[a.title, a.text]], ignore_index=True)
Nyt_TSUT.columns=['Title','Article']
Nyt_TSUT['Incident Name'] = 'Trolley Square Utah'
Nyt_TSUT['Shooter Race']='White'
Nyt_TSUT

,Title,Article,Incident Name,Shooter Race
0,Armed Man Kills 5 at Mall in Utah,"Marie Smith, a manager at the Bath and Body Wo...",Trolley Square Utah,White
1,Armed Man Kills 5 People at Utah Mall,"Ms. Smith, 23, said she had made eye contact w...",Trolley Square Utah,White
2,Sense of Loss and Unease After Salt Lake Slayings,"No motive has been established, Chief Burbank ...",Trolley Square Utah,White
3,Anti-Bosnian Backlash Feared in Utah,Ms. Roth said she received six reports on Wedn...,Trolley Square Utah,White

In [22]:
#Springwater Trail
url=['No Articles'] 
Nyt_SWT =pd.DataFrame()
for i in url: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_SWT= Nyt_SWT.append([[a.title, a.text]], ignore_index=True)
Nyt_SWT.columns=['Title','Article']
Nyt_SWT['title'] = 'NaN'
Nyt_SWT['article'] = 'NaN'
Nyt_SWT['Incident Name'] = 'Springwater Trail'
Nyt_SWT.drop(['Title','Article'], axis=1, inplace=True)
Nyt_SWT.rename(index=str, columns={'title':'Title','article':'Article'}, inplace=True)

Traceback (most recent call last):
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
XMLSyntaxError: line 1099: Tag nav invalid

In [23]:
Nyt_SWT

  Title Article      Incident Name
0   NaN     NaN  Springwater Trail

In [24]:
#Virginia Tech Urls
url68='http://www.nytimes.com/2007/04/16/us/16cnd-shooting.html'
url69='http://www.nytimes.com/2007/04/16/washington/17attorneyscnd.html'
url70='http://www.nytimes.com/2007/04/17/us/17scene.html'
url71='https://thelede.blogs.nytimes.com/2007/04/16/shooting-at-virginia-tech/'
url72='https://query.nytimes.com/gst/fullpage.html?res=9D03E4D8113FF934A25757C0A9619C8B63'
url73='http://www.nytimes.com/2007/04/17/opinion/17tue1.html'
url74='http://www.nytimes.com/2007/04/17/us/17cnd-ROOMMATE.html'
url75='http://www.nytimes.com/2007/04/17/us/17cnd-shooter.html'
url76='http://www.nytimes.com/2007/04/17/us/17tvwatch.html'
url77='http://www.nytimes.com/2007/04/17/us/17cnd-virginia.html'
url78='https://query.nytimes.com/gst/fullpage.html?res=9F01E1D7113FF934A25757C0A9619C8B63'
url79='http://www.nytimes.com/2007/04/17/us/18bloggerscnd.html'
url80='http://www.nytimes.com/2007/04/17/us/17cnd-victims.html'
url81='http://www.nytimes.com/2007/04/17/us/17virginia.html'
url82='http://www.nytimes.com/2007/04/17/us/shootings-timeline.html'
url83='http://www.nytimes.com/2007/04/17/us/18gunmanCND.html'
url84='http://www.nytimes.com/2007/04/17/us/17victims.html'
url85='https://thecaucus.blogs.nytimes.com/2007/04/17/obama-postpones-speech/'
url86='https://empirezone.blogs.nytimes.com/2007/04/17/bloomberg-a-day-to-grieve-and-pray/'
url87='https://learning.blogs.nytimes.com/2007/04/18/campus-catastrophe/'
url88='http://www.nytimes.com/2007/04/18/us/18campus.html'
url89='http://www.nytimes.com/2007/04/18/us/18mental.html'
url90='http://www.nytimes.com/2007/04/18/opinion/l18virginia.html'
url91='http://www.nytimes.com/2007/04/18/us/18pistols.html'
url92='http://www.nytimes.com/2007/04/18/us/18virginia.html'
url93='https://query.nytimes.com/gst/fullpage.html?res=9807E6DC1E3FF93BA25757C0A9619C8B63'
url94='https://query.nytimes.com/gst/fullpage.html?res=9E04E6DB1E3FF93BA25757C0A9619C8B63'
url95='http://www.nytimes.com/2007/04/18/world/asia/18cnd-korea.html'
url96='https://query.nytimes.com/gst/fullpage.html?res=9C0DE1DC1E3FF93BA25757C0A9619C8B63'
url97='http://www.nytimes.com/2007/04/18/us/18school.html'
url98='http://www.nytimes.com/2007/04/18/us/18cnd-virginia.html'
url99='https://thelede.blogs.nytimes.com/2007/04/18/updates-on-virginia-tech/'
url100='https://opinionator.blogs.nytimes.com/2007/04/18/searching-for-a-scapegoat/'
url101='http://www.nytimes.com/2007/04/19/us/19gunman.html'
url102='http://www.nytimes.com/2007/04/19/opinion/l19virginia.html'
url103='http://www.nytimes.com/2007/04/19/arts/19scre.html'
url104='http://www.nytimes.com/2007/04/19/arts/television/19watc.html'
url105='http://www.nytimes.com/2007/04/19/us/19cnd-Virginia.html'
url106='http://www.nytimes.com/2007/04/19/us/19korea.html'
url107='http://www.nytimes.com/2007/04/19/us/19professor.html'
url108='http://www.nytimes.com/2007/04/19/us/19grief.html'
url109='https://query.nytimes.com/gst/fullpage.html?res=9B05E0D81E3FF93AA25757C0A9619C8B63'
url110='http://www.nytimes.com/2007/04/19/us/19nbc.html'
url111='https://thelede.blogs.nytimes.com/2007/04/19/chos-manifesto-everywhere/'
url112='http://www.nytimes.com/2007/04/20/us/20cnd-virginia.html'
url113='http://www.nytimes.com/2007/04/20/us/20radio.html'
url114='http://www.nytimes.com/2007/04/20/us/20virginia.html'
url115='http://www.nytimes.com/2007/04/20/us/20english.html'
url116='http://www.nytimes.com/2007/04/20/opinion/20whitcomb.html'
url117='https://learning.blogs.nytimes.com/2007/04/20/feeling-for-answers/'
url118='https://thegraduates.blogs.nytimes.com/2007/04/20/a-killers-media-wish-fulfilled/'
url119='http://www.nytimes.com/2007/04/21/us/21virginia.html'
url120='http://www.nytimes.com/2007/04/22/us/22vatech.html'
url121='http://www.nytimes.com/2007/04/22/education/edlife/pappano.html'
url122='http://www.nytimes.com/2007/04/22/weekinreview/22carey.html'
url123='http://www.nytimes.com/2007/04/23/us/23church.html'
url124='http://www.nytimes.com/2007/04/23/movies/23movi.html'
url125='http://www.nytimes.com/2007/04/23/us/23cnd-virginia.html'

In [25]:
#Virginia Tech
urls=[url68, url69,url70,url71,url72,url73,url74,url75,url76,url77,url78,url79,url80,url81,url82,url83,url84,url85,
     url86,url87,url88,url89,url90,url91,url92,url93,url94,url95,url96,url97,url98,url99,url100,url101,url102,url103
     ,url104,url105,url106,url107,url108,url109,url110,url111,url112,url113,url114,url115,url116,url117,url118,url119,
     url120,url121,url122,url123,url124,url125]
Nyt_VT =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_VT= Nyt_VT.append([[a.title, a.text]], ignore_index=True)
Nyt_VT.columns=['Title','Article']
Nyt_VT['Incident Name'] = 'Virginia Tech University'
Nyt_VT['Shooter Race']='Asian'
Nyt_VT

,Title,Article,Incident Name,Shooter Race
0,Virginia Tech Shooting Leaves 33 Dead,Photo\n\nThirty-three people were killed Monda...,Virginia Tech University,Asian
1,Gonzales Hearing Delayed After Virginia Tech S...,"WASHINGTON, April 16 — The Senate Judiciary Co...",Virginia Tech University,Asian
2,"Drumbeat of Shots, Broken by Pauses to Reload","BLACKSBURG, Va., April 16 — The gunshots were ...",Virginia Tech University,Asian
3,Shooting at Virginia Tech,Evening News Reports Before Punching Out | 7:0...,Virginia Tech University,Asian
4,QUOTATION OF THE DAY,''I was crying. I was worried that the guy wit...,Virginia Tech University,Asian
5,Eight Years After Columbine,Yesterday’s mass shooting at Virginia Tech — t...,Virginia Tech University,Asian
6,Roommates Describe Gunman as Loner,"BLACKSBURG, Va., April 17 — He was a stranger ...",Virginia Tech University,Asian
7,Gunman Is Described as Quiet and 'Always by Hi...,"Cho Seung-Hui, who was identified today as the...",Virginia Tech University,Asian
8,Deadly Rampage and No Loss for Words,Television anchors said over and over that the...,Virginia Tech University,Asian
9,Faculty Was Concerned About Gunman,Photo\n\nThe gunman who killed 32 people and h...,Virginia Tech University,Asian
10,32 Shot Dead in Virginia,"Thirty-two people were killed, along with a gu...",Virginia Tech University,Asian
11,Campus Goes Online for Information and Comfort,"For the Virginia Tech community, changing info...",Virginia Tech University,Asian
12,Virginia Tech Victims,"Brian Bluhm: Loved His Friends\n\nBrian Bluhm,...",Virginia Tech University,Asian
13,Virginia Gunman Identified as a Student,Photo\n\nThe gunman who killed 32 people and h...,Virginia Tech University,Asian
14,Major Fatal Campus Shootings,We’re interested in your feedback on this page...,Virginia Tech University,Asian
15,Gunman Was ‘Always by Himself’,"BLACKSBURG, Va., April 17 — Cho Seung-Hui rare...",Virginia Tech University,Asian
16,Victims of Shooting Are Remembered,"BLACKSBURG, Va., April 17 — Ryan Clark was kno...",Virginia Tech University,Asian
17,Obama Postpones Speech,Senator Barack Obama has postponed a foreign p...,Virginia Tech University,Asian
18,Bloomberg: 'A Day to Grieve and Pray',A day after a student killed 32 people and him...,Virginia Tech University,Asian
19,Campus Catastrophe,Note: This lesson was originally published on ...,Virginia Tech University,Asian
20,Unsettled Day on Campuses Around U.S.,"Universities in Oklahoma, Tennessee and Texas ...",Virginia Tech University,Asian
21,"Taking a Break Between Shootings Is Unusual, b...",The long delay between the first and the secon...,Virginia Tech University,Asian
22,"Horror at Virginia Tech, Then the Hard Questio...",The University of Texas shooting more than 40 ...,Virginia Tech University,Asian
23,Shooting Rekindles Issues of Gun Rights and Re...,"Five weeks ago, a Virginia Tech student walked...",Virginia Tech University,Asian
24,Two-Hour Delay Is Linked to Bad Lead,"Photo\n\nBLACKSBURG, Va., April 17 — The polic...",Virginia Tech University,Asian
25,"Horror at Virginia Tech, Then the Hard Questions",\n\nTo the Editor:\n\nRe ''32 Shot Dead in Vir...,Virginia Tech University,Asian
26,Shooting Rekindles Issues of Gun Rights and Re...,"CORRECTION APPENDED\n\nFive weeks ago, a Virgi...",Virginia Tech University,Asian
27,South Koreans React to Shooting in Virginia,The news hit particularly hard here because so...,Virginia Tech University,Asian
28,Unsettled Day On Campuses Around U.S.,"Universities in Oklahoma, Tennessee and Texas ...",Virginia Tech University,Asian
29,"For School, Several Ties to Shootings","CHANTILLY, Va., April 17 — “Heaven gained an a...",Virginia Tech University,Asian
30,"Gunman Sent Photos, Video and Writings to NBC",Photo\n\n“I didn’t have to do this. I could ha...,Virginia Tech University,Asian
31,Updates on Virginia Tech,Coverage of Mr. Cho’s Manifesto Continues Here...,Virginia Tech University,Asian
32,Searching for a Scapegoat,Give the Virginia Tech administration a break:...,Virginia Tech University,Asian
33,Officials Knew Troubled State of Killer in ’05,"BLACKSBURG, Va., April 18 — Campus authorities...",Virginia Tech University,Asian
34,"The Portrait of a Gunman, and of a Society (9 ...",That means money for early childhood education...,Virginia Tech University,Asian
35,"Online, Students Say ‘Reach Out to Loners’",As masses of mourners assemble at sites like F...,Virginia Tech University,Asian
36,"Amid Chaos, One Notably Restrained Voice",“And how would you describe his facial manner ...,Virginia Tech University,Asian
37,University Says It Wasn’t Involved in Gunman’s...,Governor Kaine said he had appointed Gerald Ma...,Virginia Tech University,Asian
38,Korean-Americans Brace for Problems in Wake of...,Fearful of the backlash that Arab-Americans an...,Virginia Tech University,Asian
39,Professor’s Violent Death Came Where He Sought...,“This was a man who gave his ultimate for his ...,Virginia Tech University,Asian
40,"Amid the Chaos of Deaths, a Minister Attends t...","At the command center, Mr. Evans met the offic...",Virginia Tech University,Asian
41,"The Portrait of a Gunman, and of a Society",\n\nTo the Editor:\n\nRe ''In Words and Silenc...,Virginia Tech University,Asian
42,Package Forced NBC to Make Tough Decisions,Mr. Capus said Mr. Patton and everyone else at...,Virginia Tech University,Asian
43,"Cho's Manifesto, Everywhere",After the news media spent days dealing with u...,Virginia Tech University,Asian
44,The New York Times,Photo\n\nGrieving and sadness over the nation’...,Virginia Tech University,Asian
45,Talk Radio Tries for Humor and a Political Adv...,"This, after all, is an incident in which many ...",Virginia Tech University,Asian
46,University Explains the Return of Troubled Stu...,Investigators now believe that after Mr. Cho l...,Virginia Tech University,Asian
47,Anger of Killer Was on Exhibit in His Writings,"BLACKSBURG, Va., April 19 — More than anyone e...",Virginia Tech University,Asian
48,Building a Better Lockdown,"So how did we end up here, yet again? Why are ...",Virginia Tech University,Asian
49,Feeling for Answers,Note: This lesson was originally published on ...,Virginia Tech University,Asian
50,A Killer's Media Wish Fulfilled,Every day in my Oral Traditions of Musicianshi...,Virginia Tech University,Asian
51,Memorial Services Held in U.S. and Around World,The statement was the first indication the fam...,Virginia Tech University,Asian
52,"Before Deadly Rage, a Life Consumed by a Troub...","No one could understand why. On Friday, his si...",Virginia Tech University,Asian
53,Conduct Unbecoming,"James M. Sumner, president of the Common Appli...",Virginia Tech University,Asian
54,Mental Health and Disorders,The evidence that this happened over the month...,Virginia Tech University,Asian
55,Praying for a ‘Troubled Soul’ and Mourning for...,"Photo\n\nCENTREVILLE, Va., April 22 — Addressi...",Virginia Tech University,Asian
56,Virginia Tech killings,The mass shooting on the Virginia Tech campus ...,Virginia Tech University,Asian
57,Virginia Tech Students Return to Classes,"BLACKSBURG, Va., April 23 — Classes resumed at...",Virginia Tech University,Asian

In [26]:
#Crandon WI
url126='http://www.nytimes.com/2007/10/08/us/08wisconsin.html'
url127='http://www.nytimes.com/2007/10/08/us/08cnd-shoot.html'
url128='http://www.nytimes.com/2007/10/09/us/09rampage.html'
url129='http://www.nytimes.com/2007/10/10/us/10rampage.html'
urls=[url126,url127,url128,url129]
Nyt_CWI =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_CWI= Nyt_CWI.append([[a.title, a.text]], ignore_index=True)
Nyt_CWI.columns=['Title','Article']
Nyt_CWI['Incident Name'] = 'Apt in Crandon, WI'
Nyt_CWI['Shooter Race']='White'
Nyt_CWI

,Title,Article,Incident Name,Shooter Race
0,Gunman Kills Six in Wisconsin Town,"CRANDON, Wis., Oct. 7 (AP) — An off-duty sheri...","Apt in Crandon, WI",White
1,Dispute Is Cited in Wisconsin Shooting,Some kind of dispute was behind the massacre e...,"Apt in Crandon, WI",White
2,"A Tiny Town, Suddenly Smaller by Seven, Mourns...","Before 3 a.m. Sunday, state authorities said, ...","Apt in Crandon, WI",White
3,Gunman in Rampage Had Been Certified to Be an ...,"But state officials, who are leading the inves...","Apt in Crandon, WI",White

In [27]:
#Cleveland HS
url130='http://www.nytimes.com/2007/10/11/us/11cleveland.html'
url131='http://www.nytimes.com/2007/10/12/us/12cleveland.html'
urls=[url130,url131]
Nyt_CHS =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_CHS= Nyt_CHS.append([[a.title, a.text]], ignore_index=True)
Nyt_CHS.columns=['Title','Article']
Nyt_CHS['Incident Name'] = 'SuccessTech Academy'
Nyt_CHS['Shooter Race']='White'
Nyt_CHS

,Title,Article,Incident Name,Shooter Race
0,"Student, 14, Shoots 4 and Kills Himself in Cle...",Mychael said she darted down a flight of stair...,SuccessTech Academy,White
1,Short but Troubled Life Ended in Shooting and ...,After looking at the swarm of police cars arri...,SuccessTech Academy,White

In [28]:
#Sagina MI
url132='https://query.nytimes.com/gst/fullpage.html?res=9A03EED91230F936A15753C1A9619C8B63'
Nyt_SMI =pd.DataFrame()
a=Article(url132, language='en')
a.download()
a.parse()
Nyt_SMI= Nyt_SMI.append([[a.title, a.text]], ignore_index=True)
Nyt_SMI.columns=['Title','Article']
Nyt_SMI['Incident Name'] = 'South Middle School Football Game'
Nyt_SMI['Shooter Race']='African American'
Nyt_SMI

,Title,Article,Incident Name,Shooter Race
0,4 ARE SHOT AT FOOTBALL GAME IN MICHIGAN,\n\n\n\nPhoto: Four students at a middle schoo...,South Middle School Football Game,African American

In [29]:
#Westroads Mall
url244='http://www.nytimes.com/2007/12/09/us/09mall.html'
url245='http://www.nytimes.com/2007/12/06/us/06omaha.html'
url246='http://www.nytimes.com/2007/12/06/us/06cnd-shoot.html'
url247='http://www.nytimes.com/2007/12/07/us/07store.html'
url248='http://www.nytimes.com/2007/12/07/us/07mall.html'
urls=[url244,url245,url246,url247,url248]
Nyt_WM =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_WM= Nyt_WM.append([[a.title, a.text]], ignore_index=True)
Nyt_WM.columns=['Title','Article']
Nyt_WM['Incident Name'] = 'Westroads Mall'
Nyt_WM['Shooter Race']='White'
Nyt_WM

,Title,Article,Incident Name,Shooter Race
0,"Three Days After Killings, Mall Re-Opens for B...","OMAHA, Dec. 8 (AP) — With extra security on ha...",Westroads Mall,White
1,Gunman at an Omaha Mall Kills 8 and Himself,"The group pushed every table, rack and garbage...",Westroads Mall,White
2,Details of Omaha Shooting Emerge,“These were innocent people going about their ...,Westroads Mall,White
3,Stylish Surroundings Are Shattered by Killings,"Janice Hopkins, who had taken a seasonal job w...",Westroads Mall,White
4,Searching for Clues to a Young Killer’s Motiva...,"In the aftermath of the shooting, the picture ...",Westroads Mall,White

In [30]:
#Arvada, CO
url133='http://www.nytimes.com/2007/12/10/us/10shooting.html'
url134='http://www.nytimes.com/2007/12/10/us/10cnd-shoot.html'
url135='http://www.nytimes.com/2007/12/11/us/11churches.html'
urls=[url133,url134,url135]
Nyt_ACO =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_ACO= Nyt_ACO.append([[a.title, a.text]], ignore_index=True)
Nyt_ACO.columns=['Title','Article']
Nyt_ACO['Incident Name'] = 'Youth with a Mission and New Life Church'
Nyt_ACO['Shooter Race']='White'
Nyt_ACO

,Title,Article,Incident Name,Shooter Race
0,2 Fatal Shootings at Colorado Religious Sites,Photo\n\nA gunman and four people were killed ...,Youth with a Mission and New Life Church,White
1,"Man Committed Both Colo. Shootings, Police Say",The security guard who shot and killed Mr. Mur...,Youth with a Mission and New Life Church,White
2,Police Tie Colorado Church Shootings to One Gu...,Officials said they were still investigating w...,Youth with a Mission and New Life Church,White

In [31]:
#Tyler Tex 
url136='http://www.nytimes.com/2005/02/27/national/killings-rattle-an-east-texas-town-better-known-for-its-roses.html?mcubz=0&_r=0'
Nyt_SCC =pd.DataFrame()
a=Article(url136, language='en')
a.download()
a.parse()
Nyt_SCC= Nyt_SCC.append([[a.title, a.text]], ignore_index=True)
Nyt_SCC.columns=['Title','Article']
Nyt_SCC['Incident Name'] = 'Smith County Courthouse'
Nyt_SCC['Shooter Race']='Latin American'
Nyt_SCC

,Title,Article,Incident Name,Shooter Race
0,Killings Rattle an East Texas Town Better Know...,">\n\nTYLER, Tex., Feb. 26 (AP) - Blake Bailey ...",Smith County Courthouse,Latin American

In [32]:
#Lakewood Coffee Shop
url137='https://query.nytimes.com/gst/fullpage.html?res=9D01E5DA1E3DF933A05752C1A96F9C8B63'
url138='http://www.nytimes.com/2009/12/01/us/01tacoma.html'
url139='http://www.nytimes.com/2009/12/02/us/02tacoma.html'
url140='http://www.nytimes.com/2009/12/04/us/04brfs-CHARGEDINPOL_BRF.html'
urls=[url137,url138,url139,url140]
Nyt_LC =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_LC= Nyt_LC.append([[a.title, a.text]], ignore_index=True)
Nyt_LC.columns=['Title','Article']
Nyt_LC['Incident Name'] = 'Parkland Coffee Shop'
Nyt_LC['Shooter Race']='African American'
Nyt_LC

,Title,Article,Incident Name,Shooter Race
0,4 Police Officers Die in Coffee Shop Ambush,Four uniformed police officers were shot to de...,Parkland Coffee Shop,African American
1,Tacoma Suspect Said to Threaten to Shoot Officers,"The police offered a reward of $125,000 for in...",Parkland Coffee Shop,African American
2,Suspect Slain in Seattle; 4 Are Held as Flight...,Charging documents describe a series of car ri...,Parkland Coffee Shop,African American
3,Washington: Charged in Police Killing,A half brother of the man accused of gunning d...,Parkland Coffee Shop,African American

In [33]:
#Fort Hood URLS
url141='https://thelede.blogs.nytimes.com/2009/11/05/reports-of-mass-shooting-at-fort-hood/'
url142='http://www.nytimes.com/2009/11/06/us/06forthood.html'
url143='http://www.nytimes.com/2009/11/06/us/06suspect.html'
url144='http://www.nytimes.com/2009/11/06/us/06victims.html'
url145='https://thelede.blogs.nytimes.com/2009/11/06/latest-updates-on-shootings-at-fort-hood/'
url146='https://learning.blogs.nytimes.com/2009/11/06/responding-to-news-of-the-shootings-at-fort-hood/'
url147='http://www.nytimes.com/2009/11/07/us/07forthood.html'
url148='http://www.nytimes.com/2009/11/07/us/07suspect.html'
url149='https://atwar.blogs.nytimes.com/2009/11/06/coverage-of-the-fort-hood-shootings/'
url150='http://www.nytimes.com/2009/11/07/us/07victims.html'
url151='http://www.nytimes.com/2009/11/07/us/07police.html'
url152='https://mediadecoder.blogs.nytimes.com/2009/11/06/fox-news-channel-draws-a-large-audience-for-coverage-of-fort-hood-shootings/'
url153='https://roomfordebate.blogs.nytimes.com/2009/11/06/combat-stress-and-the-fort-hood-gunman/'
url154='http://www.nytimes.com/2009/11/07/us/07scene.html'
url155='http://www.nytimes.com/2009/11/07/opinion/07cleland.html'
url156='http://www.nytimes.com/2009/11/07/us/07muslim.html'
url157='http://www.nytimes.com/2009/11/08/us/politics/08address.html'
url158='https://thecaucus.blogs.nytimes.com/2009/11/07/saturday-word-fort-hood-and-health-care/'
url159='https://prescriptions.blogs.nytimes.com/2009/11/07/obamas-in-the-house/'
url160='http://www.nytimes.com/2009/11/08/weekinreview/08goode.html'
url161='http://www.nytimes.com/2009/11/08/us/08forthood.html'
url162='http://www.nytimes.com/2009/11/08/us/08stress.html'
url163='http://www.nytimes.com/2009/11/08/us/08victims.html'
url164='http://www.nytimes.com/2009/11/08/us/08investigate.html'
url165='http://www.nytimes.com/2009/11/08/world/asia/08troops.html'
url166='http://www.nytimes.com/2009/11/09/us/politics/09casey.html'
url167='http://www.nytimes.com/2009/11/09/us/09muslim.html'
url168='http://www.nytimes.com/2009/11/09/us/09reconstruct.html'
url169='http://www.nytimes.com/2009/11/10/us/10hood.html'
url170='http://www.nytimes.com/2009/11/10/us/10inquire.html'
url171='https://opinionator.blogs.nytimes.com/2009/11/09/the-meaning-of-fort-hood/'
url172='http://www.nytimes.com/2009/11/10/opinion/l10hood.html'
url173='https://query.nytimes.com/gst/fullpage.html?res=980CE0DA1339F933A25752C1A96F9C8B63'
url174='http://www.nytimes.com/2009/11/11/opinion/l11hood.html'
url175='https://thecaucus.blogs.nytimes.com/2009/11/11/the-early-word-soldiers-and-wars/'
url176='http://www.nytimes.com/2009/11/12/us/12inquire.html'
url177='http://www.nytimes.com/2009/11/12/us/12hood.html'

In [34]:
#Fort Hood
urls=[url141,url142,url143,url144,url145,url146,url147,url148,url149,url150,url151,url152,url153,url154,url155,url156,
     url157,url158,url159,url160,url161,url162,url163,url164,url165,url166,url167,url168,url169,url170,url171,
     url172,url173,url174,url175,url176,url177]
Nyt_FtH =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_FtH= Nyt_FtH.append([[a.title, a.text]], ignore_index=True)
Nyt_FtH.columns=['Title','Article']
Nyt_FtH['Incident Name'] = 'Fort Hood'
Nyt_FtH['Shooter Race']='White'
Nyt_FtH

,Title,Article,Incident Name,Shooter Race
0,Mass Shooting at Fort Hood,Ben Sklar/Getty Images\n\nAt a news conference...,Fort Hood,White
1,Army Doctor Held as Fort Hood Rampage Kills 12,Photo\n\nAn Army psychiatrist facing deploymen...,Fort Hood,White
2,Fort Hood Suspect Was ‘Mortified’ About Deploy...,"WASHINGTON — Born and reared in Virginia, the ...",Fort Hood,White
3,Shooting Victims Flood Local Hospitals,The shootings at Fort Hood in Texas severely t...,Fort Hood,White
4,Updates on the Shootings at Fort Hood,"On Friday, The Lede is providing updates on th...",Fort Hood,White
5,Responding to News of the Shootings at Fort Hood,Ben Sklar/Getty Images\n\nAre you talking abou...,Fort Hood,White
6,Army Tests Sole-Killer Theory as Details Emerge,"Photo\n\nKILLEEN, Tex. — On Wednesday and Thur...",Fort Hood,White
7,Neighbor Says Hasan Gave Belongings Away Befor...,"Photo\n\nKILLEEN, Tex. — On Thursday morning, ...",Fort Hood,White
8,Coverage of the Fort Hood Shootings,In the aftermath of Thursday’s deadly shooting...,Fort Hood,White
9,"Dedicated, Caring, and Suddenly Lost at Home",Photo\n\nThe stress of American soldiers fight...,Fort Hood,White
10,Highly Trained Sergeant Brought Down Gunman,"KILLEEN, Tex. — The police officer who brought...",Fort Hood,White
11,Fox News Channel Draws Large Audience for Cove...,Viewership for the cable news channels surged ...,Fort Hood,White
12,Combat Stress and the Fort Hood Gunman,L. M. Otero/The Associated Press\n\nMaj. Nidal...,Fort Hood,White
13,From Humdrum Day to a Scene of Chaos,"Photo\n\nFORT HOOD, Tex. — The Soldier Readine...",Fort Hood,White
14,The Forever War of the Mind,"“EVERY day I was in Vietnam, I thought about h...",Fort Hood,White
15,Muslims at Fort Voice Outrage and Ask Questions,"Photo\n\nKILLEEN, Tex. — Leaders of the vibran...",Fort Hood,White
16,Obama Offers Sympathy and Urges No ‘Jump to Co...,"WASHINGTON — President Obama, extending condol...",Fort Hood,White
17,Saturday Word: Fort Hood and Health Care,President Obama uses his weekly address this w...,Fort Hood,White
18,UPDATED: Obama Rallies House Democrats,Luke Sharrett/The New York Times\n\nPresident ...,Fort Hood,White
19,When Soldiers Snap,"Over the centuries, soldiers have often broken...",Fort Hood,White
20,Army Concludes Shootings Involved Only One Gunman,"“I’ve known my brother Nidal to be a peaceful,...",Fort Hood,White
21,Painful Stories Take a Toll on Military Therap...,"Many military professionals, meanwhile, descri...",Fort Hood,White
22,Army Releases Names of All 13 Killed in Shootings,As federal investigators continued to figure o...,Fort Hood,White
23,Investigation Into Fort Hood Shootings Turns U...,Investigators have gleaned most of their findi...,Fort Hood,White
24,All Afghan War Options by Obama Aides Said to ...,WASHINGTON — Advisers to President Obama are p...,Fort Hood,White
25,Army Chief Concerned for Muslim Troops,"The major, a 39-year-old psychiatrist, is the ...",Fort Hood,White
26,Complications Grow for Muslims Serving in U.S....,"On Sunday, the Army’s chief of staff, Gen. Geo...",Fort Hood,White
27,Fort Hood Gunman Gave Signals Before His Rampage,"In recent years, he had grown more and more vo...",Fort Hood,White
28,"Fort Hood Suspect Is Conscious, Hospital Says","The aim of both steps, the general said, is to...",Fort Hood,White
29,Fort Hood Suspect Communicated With Radical Cl...,“There was no indication that Major Hasan was ...,Fort Hood,White
30,The Meaning of Fort Hood,The Thread is an in-depth look at how major ne...,Fort Hood,White
31,As the Nation Grieves Over Fort Hood,"Judith H. Christie\n\nWynnewood, Pa., Nov. 6, ...",Fort Hood,White
32,U.S. Monitored Fort Hood Suspect Before Shooting,WASHINGTON -- Intelligence agencies intercepte...,Fort Hood,White
33,"The Fort Hood Tragedy, From Other Perspectives",To the Editor:\n\nI would like to commend Bob ...,Fort Hood,White
34,The Early Word: Soldiers and Wars,"On Veterans Day, ceremonies around the country...",Fort Hood,White
35,"Questions, Not Alarms, Met Exchanges With Cleric","Now, Congress is looking for someone to blame ...",Fort Hood,White
36,Fort Hood Hero Story Questioned,Six days after the deadly shooting rampage at ...,Fort Hood,White

In [35]:
#Binghampton URLS
url178='https://thelede.blogs.nytimes.com/2009/04/03/shooting-in-binghamton/'
url179='http://www.nytimes.com/2009/04/04/nyregion/04hostage.html'
url180='http://www.nytimes.com/2009/04/04/nyregion/04civic.html'
url181='http://www.nytimes.com/2009/04/05/nyregion/05shoot.html'
url182='http://www.nytimes.com/2009/04/05/nyregion/05suspect.html'
url183='http://www.nytimes.com/2009/04/06/nyregion/06teacher.html'
url184='http://www.nytimes.com/2009/04/06/nyregion/06victims.html'
url185='http://www.nytimes.com/2009/04/07/nyregion/07binghamton.html'
url186='http://www.nytimes.com/2009/04/08/nyregion/08binghamton.html'

In [36]:
#BingHampton Citizens Meeting
urls=[url178,url179,url180,url181,url182,url183,url184,url185,url186]
Nyt_Bing =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_Bing= Nyt_Bing.append([[a.title, a.text]], ignore_index=True)
Nyt_Bing.columns=['Title','Article']
Nyt_Bing['Incident Name'] = 'Binghamton Citizens Meeting'
Nyt_Bing['Shooter Race']='Asian'
Nyt_Bing

,Title,Article,Incident Name,Shooter Race
0,"Shooting in Binghamton, N.Y.","For more information and further developments,...",Binghamton Citizens Meeting,Asian
1,"Gunman Kills 13 and Wounds 4 at Binghamton, N....",It was the nation’s worst mass shooting since ...,Binghamton Citizens Meeting,Asian
2,"In a Town With Few Immigrants, an Unlikely Horror",By the end of the brief but terrifying episode...,Binghamton Citizens Meeting,Asian
3,"Amid Binghamton Gunfire, Pleas to Police and t...",Binghamton’s American Civic Association was fo...,Binghamton Citizens Meeting,Asian
4,"Before Killings, Hints of Plans and Grievance",Chief Zikuski said that to people close to Mr....,Binghamton Citizens Meeting,Asian
5,"Teacher Was Absent for Binghamton Shootings, N...","On Sunday morning, amid the quiet of her Bingh...",Binghamton Citizens Meeting,Asian
6,Binghamton Shooting Victims Shared a Dream of ...,"Mr. Wong married and divorced in California, b...",Binghamton Citizens Meeting,Asian
7,"Letter, Believed to Be From Binghamton Gunman,...","In a brief, taunting note that he left for the...",Binghamton Citizens Meeting,Asian
8,Police Report Few Contacts With Binghamton Gun...,"Two days later, a uniformed officer pulled Mr....",Binghamton Citizens Meeting,Asian

In [37]:
#PineLake Nursing HOme
url187='http://www.nytimes.com/2009/03/30/us/30shooting.html'
url188='http://www.nytimes.com/2009/03/31/us/31shooting.html'
urls=[url187,url188]
Nyt_PNH =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_PNH= Nyt_PNH.append([[a.title, a.text]], ignore_index=True)
Nyt_PNH.columns=['Title','Article']
Nyt_PNH['Incident Name'] = 'PineLake Nursing Home'
Nyt_PNH['Shooter Race']='White'
Nyt_PNH

,Title,Article,Incident Name,Shooter Race
0,Gunman Kills 8 at a N. Carolina Nursing Home,“He just lay down his life to protect the resi...,PineLake Nursing Home,White
1,Alleged Gunman’s Wife Worked at Nursing Home,According to records at the Moore County Sheri...,PineLake Nursing Home,White

In [38]:
#Santa Clara
url189='http://www.nytimes.com/2009/03/31/us/31brfs-MOTIVESOUGHT_BRF.html'
Nyt_SC =pd.DataFrame()
a=Article(url136, language='en')
a.download()
a.parse()
Nyt_SC= Nyt_SC.append([[a.title, a.text]], ignore_index=True)
Nyt_SC.columns=['Title','Article']
Nyt_SC['Incident Name'] = 'Santa Clara'
Nyt_SC['Shooter Race']='Asian'
Nyt_SC

,Title,Article,Incident Name,Shooter Race
0,Killings Rattle an East Texas Town Better Know...,">\n\nTYLER, Tex., Feb. 26 (AP) - Blake Bailey ...",Santa Clara,Asian

In [39]:
#Geneva County, AL
url190='http://www.nytimes.com/2009/03/12/us/12alabama.html'
url191='http://www.nytimes.com/2009/03/11/us/11alabama.html'
url192='https://thelede.blogs.nytimes.com/2009/03/11/the-aftermath-in-samson-ala/'
urls=[url190,url191,url192]
Nyt_GCAL =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_GCAL= Nyt_GCAL.append([[a.title, a.text]], ignore_index=True)
Nyt_GCAL.columns=['Title','Article']
Nyt_GCAL['Incident Name'] = 'Geneva County, Alabama'
Nyt_GCAL['Shooter Race']='White'
Nyt_GCAL

,Title,Article,Incident Name,Shooter Race
0,Officials Identify Alabama Gunman,"Photo\n\nSAMSON, Ala. — The gunman, wearing a ...","Geneva County, Alabama",White
1,"Gunman Kills 10 in Alabama, Then Takes His Life",Photo\n\nA gunman shot and killed at least 10 ...,"Geneva County, Alabama",White
2,"The Aftermath in Samson, Ala.",This post will follow today’s developments fro...,"Geneva County, Alabama",White

In [40]:
#Covina Party
url193='http://www.nytimes.com/2008/12/30/us/30brfs-005.html'
url194='http://www.nytimes.com/2008/12/26/us/26Santa.html'
url195='http://www.nytimes.com/2008/12/27/us/27shooting.html'
url196='http://www.nytimes.com/2008/12/27/us/27shoot.html'
urls=[url193,url194,url195,url196]
Nyt_Cov =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_Cov= Nyt_Cov.append([[a.title, a.text]], ignore_index=True)
Nyt_Cov.columns=['Title','Article']
Nyt_Cov['Incident Name'] = 'Covina, California'
Nyt_Cov['Shooter Race']='White'
Nyt_Cov

,Title,Article,Incident Name,Shooter Race
0,California: Canada Not in Killer’s Escape Plans,The authorities have corrected a detail in the...,"Covina, California",White
1,Man in a Santa Suit Kills at Least 8 at a Party,"Photo\n\nCOVINA, Calif. — A man in a Santa Cla...","Covina, California",White
2,Gunman in Santa Suit Had Ticket to Canada,Chief Raney said Mr. Pardo and his wife had fi...,"Covina, California",White
3,"Attacker at Party Had Escape Plan, Police Say","On Friday, 9 of the 25 guests at the Christmas...","Covina, California",White

In [41]:
#University of Central Arkansas
url197='http://www.nytimes.com/2008/10/28/us/28arkansas.html'
url198='http://www.nytimes.com/2008/10/27/us/27campus.html'
urls=[url197,url198]
Nyt_UCA =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_UCA= Nyt_UCA.append([[a.title, a.text]], ignore_index=True)
Nyt_UCA.columns=['Title','Article']
Nyt_UCA['Incident Name'] = 'University of Central Arkansas'
Nyt_UCA['Shooter Race']='African American'
Nyt_UCA

,Title,Article,Incident Name,Shooter Race
0,2 Are Killed in Shooting on a Campus in Arkansas,Numerous witnesses at the scene provided accou...,University of Central Arkansas,African American
1,Two Dead in Shooting on Campus,"LITTLE ROCK, Ark. — Two people were reported s...",University of Central Arkansas,African American

In [42]:
#South Mountain Trail
url=['No Articles'] 
Nyt_SMT =pd.DataFrame()
for i in url: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_SMT= Nyt_SMT.append([[a.title, a.text]], ignore_index=True)
Nyt_SMT.columns=['Title','Article']
Nyt_SMT['title'] = 'NaN'
Nyt_SMT['article'] = 'NaN'
Nyt_SMT['Incident Name'] = 'South Mountain Trail'
Nyt_SMT.drop(['Title','Article'], axis=1, inplace=True)
Nyt_SMT.rename(index=str, columns={'title':'Title','article':'Article'}, inplace=True)

Traceback (most recent call last):
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
XMLSyntaxError: line 1010: Tag nav invalid

In [43]:
Nyt_SMT

  Title Article         Incident Name
0   NaN     NaN  South Mountain Trail

In [44]:
#Altantis Plastics
url199='http://www.nytimes.com/2008/06/25/us/26kentuckycnd.html'
url200='http://www.nytimes.com/2008/06/26/us/26factory.html'
urls=[url199,url200]
Nyt_AP =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_AP= Nyt_AP.append([[a.title, a.text]], ignore_index=True)
Nyt_AP.columns=['Title','Article']
Nyt_AP['Incident Name'] = 'Atlantis Plastics'
Nyt_AP['Shooter Race']='White'
Nyt_AP

,Title,Article,Incident Name,Shooter Race
0,Man in Kentucky Kills 5 Co-Workers,"HENDERSON, Ky. — A man who worked at a Henders...",Atlantis Plastics,White
1,Man Who Killed Five People in Kentucky Had Cal...,"HENDERSON, Ky. — A man who killed five people ...",Atlantis Plastics,White

In [45]:
#Northern Illinois Univeristy
url208='http://www.nytimes.com/2008/02/14/us/15cnd-shooting.html'
url209='http://www.nytimes.com/2008/02/15/us/15shoot.html'
url210='http://www.nytimes.com/2008/02/15/us/15cnd-victims.html'
url211='http://www.nytimes.com/2008/02/15/us/15cnd-shoot.html'
url212='https://thelede.blogs.nytimes.com/2008/02/15/a-string-of-campus-gun-rampages/'
url213='https://cityroom.blogs.nytimes.com/2008/02/15/bloomberg-on-illegal-guns-and-rampages/'
url214='https://thelede.blogs.nytimes.com/2008/02/15/digital-traces-of-the-niu-shooting/'
url215='https://thelede.blogs.nytimes.com/2008/02/15/blogging-to-grips-with-a-massacre/'
url216='http://www.nytimes.com/2008/02/16/us/16campus.html'
url217='http://www.nytimes.com/2008/02/16/us/16gunman.html'
url218='http://www.nytimes.com/2008/02/16/us/16shooting.html'
url219='http://www.nytimes.com/2008/02/17/us/17illinois.html'
url220='http://www.nytimes.com/2008/02/18/movies/18arts-CAMPUSVIOLEN_BRF.html'
url221='http://www.nytimes.com/2008/02/18/business/media/18college.html'
url222='http://www.nytimes.com/2008/02/19/us/19depress.html'
url223='http://www.nytimes.com/2008/02/20/us/20shooter.html'
urls=[url208,url209,url210,url211,url212,url213,url214,url215,url216,url217,url218,url219,url220,
     url221,url222,url223]
Nyt_NIU =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_NIU= Nyt_NIU.append([[a.title, a.text]], ignore_index=True)
Nyt_NIU.columns=['Title','Article']
Nyt_NIU['Incident Name'] = 'Northern Illinois University'
Nyt_NIU['Shooter Race']='White'
Nyt_NIU

,Title,Article,Incident Name,Shooter Race
0,Gunman Kills 5 on Illinois Campus,"The gunman, whom the authorities did not immed...",Northern Illinois University,White
1,Gunman Slays 6 at N. Illinois University,"Kevin McEnery, 19, one of the public universit...",Northern Illinois University,White
2,Profiles of the Victims,The following six died as a result of the shoo...,Northern Illinois University,White
3,Gunman Was Once ‘Revered’ on Campus,"On Thursday afternoon, he parked near the 200-...",Northern Illinois University,White
4,A String of Campus Gun Rampages,"If the news from DeKalb, Ill. — a gunman burst...",Northern Illinois University,White
5,Bloomberg on Illegal Guns and Rampages,"Updated, 1:38 p.m. | The morning after the sho...",Northern Illinois University,White
6,Digital Traces of the N.I.U. Shooting,Updated 4:00 p.m. Eastern\n\nAs more specifics...,Northern Illinois University,White
7,Coming to Grips (Online) With Shooting,Here is a sampling of notable online commentar...,Northern Illinois University,White
8,Gaps Likely to Persist in Campus Security,"As a parent, Jay Spradling feels the same fear...",Northern Illinois University,White
9,Gunman Showed Few Hints of Trouble,Officials said the only hint of trouble from M...,Northern Illinois University,White
10,Grief and Questions After Deadly Shootings,"The dealer, Eric Thompson, said Mr. Kazmiercza...",Northern Illinois University,White
11,"After Shootings, Illinois Campus Prepares to M...","So far, law enforcement officials do not have ...",Northern Illinois University,White
12,Campus Violence Film Has Release Date,Delayed after the deadly shootings last year a...,Northern Illinois University,White
13,"First on the Scene, Again, Is the College News...",When news breaks on college campuses — as it d...,Northern Illinois University,White
14,Reports of Gunman’s Use of Antidepressant Rene...,"The girlfriend, Jessica Baty, said in an inter...",Northern Illinois University,White
15,"Gunman Hid His Tracks, Officials Say",CHICAGO — The man who killed five students at ...,Northern Illinois University,White

In [46]:
#Kirkwood City Hall
url204='http://www.nytimes.com/2008/02/09/us/09missouri.html'
url205='http://www.nytimes.com/2008/02/08/us/08cnd-missouri.html'
url206='http://www.nytimes.com/2008/02/08/us/08missouri.html'
url207='http://www.nytimes.com/2008/02/07/us/07cnd-shoot.html'
urls=[url204,url205,url206,url207]
Nyt_KCH =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_KCH= Nyt_KCH.append([[a.title, a.text]], ignore_index=True)
Nyt_KCH.columns=['Title','Article']
Nyt_KCH['Incident Name'] = 'Kirkwood City Hall'
Nyt_KCH['Shooter Race']='African American'
Nyt_KCH

,Title,Article,Incident Name,Shooter Race
0,"In Missouri, City Asks What Made Killer Snap",The authorities said Mr. Thornton arrived at C...,Kirkwood City Hall,African American
1,Mourning in Missouri as Shooter’s Motives Emerge,Mr. Thornton appeared to have hit a tipping po...,Kirkwood City Hall,African American
2,Gunman Kills 5 People at City Council Meeting,The authorities would not identify the dead la...,Kirkwood City Hall,African American
3,Officer Killed in Armed Standoff,"Photo\n\nKIRKWOOD, Mo. (AP) -- Five people, an...",Kirkwood City Hall,African American

In [47]:
#Carnation, Washington
url=['No Articles'] 
Nyt_CW =pd.DataFrame()
for i in url: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_CW= Nyt_CW.append([[a.title, a.text]], ignore_index=True)
Nyt_CW.columns=['Title','Article']
Nyt_CW['title'] = 'NaN'
Nyt_CW['article'] = 'NaN'
Nyt_CW['Incident Name'] = 'Carnation, Washington'
Nyt_CW.drop(['Title','Article'], axis=1, inplace=True)
Nyt_CW.rename(index=str, columns={'title':'Title','article':'Article'}, inplace=True)
Nyt_CW

Traceback (most recent call last):
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/ThomasPLapinger/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
XMLSyntaxError: line 1178: Tag nav invalid

  Title Article          Incident Name
0   NaN     NaN  Carnation, Washington

In [48]:
#Mojave HS
url201='http://www.nytimes.com/2007/12/12/us/12vegas.html'
url202='http://www.nytimes.com/2007/12/13/us/13vegas.html'
url203='http://www.nytimes.com/2007/12/14/us/14vegas.html'
urls=[url201,url202,url203]
Nyt_MHS =pd.DataFrame()
for i in urls: 
    a=Article(i, language='en')
    a.download()
    a.parse()
    Nyt_MHS= Nyt_MHS.append([[a.title, a.text]], ignore_index=True)
Nyt_MHS.columns=['Title','Article']
Nyt_MHS['Incident Name'] = 'Mojave High School'
Nyt_MHS['Shooter Race']='African American'
Nyt_MHS

,Title,Article,Incident Name,Shooter Race
0,6 People Shot After Exiting a School Bus in La...,LAS VEGAS (AP) — Assailants on Tuesday shot si...,Mojave High School,African American
1,Gunmen Sought in Bus Stop Shooting,LAS VEGAS (AP) — The police continued to searc...,Mojave High School,African American
2,Arrest Is Made in Bus Shooting,LAS VEGAS (AP) — An 18-year-old man was arrest...,Mojave High School,African American

In [49]:
NYT_2000s=pd.concat([Nyt_ET, Nyt_ASL, Nyt_NI, Nyt_SHS, Nyt_UofA, Nyt_CARU, Nyt_LM, Nyt_WCC, Nyt_BW, Nyt_AV, Nyt_Brook,
                     Nyt_RHS, Nyt_GPO, Nyt_SHP, Nyt_EES, Nyt_OHS, Nyt_DU, Nyt_Amish, Nyt_TSUT, Nyt_SWT, Nyt_VT, Nyt_CWI,
                     Nyt_CHS, Nyt_SMI, Nyt_ACO, Nyt_WM, Nyt_SCC, Nyt_LC, Nyt_FtH, Nyt_PNH, Nyt_SC, Nyt_GCAL, Nyt_Cov, Nyt_UCA, Nyt_SMT, Nyt_AP, Nyt_NIU, Nyt_KCH, 
                     Nyt_CW, Nyt_MHS, Nyt_Bing])

In [55]:
for i in NYT_2000s:
    i.replace('N.R.A.','NRA')

In [51]:
NYT_2000s.to_csv('NYT 2000s Shootings-2.csv',index=False, encoding='utf-8')